[build-system]
requires = ["flit_core >=2,<4"]
build-backend = "flit_core.buildapi"

[tool.flit.metadata]
module = "get_cpt"
author = "bouziot"
home-page = "https://github.com/mattijn/get-cpt"
classifiers = ["License :: OSI Approved :: MIT License"]
description-file = "README.md"

